name: Деплой документации

on:
  workflow_run:
    workflows: ["Тесты"]
    types:
      - completed

permissions:
  contents: write # Разрешает пуш в gh-pages

jobs:
  deploy_docs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
      - name: Настройка uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Установка зависимостей
        run: make sync
      - name: Деплой документации
        run: make deploy-docs
